firstNumber = +prompt('For mathematical calculations (addition, subtraction, multiplication, division) enter the first number');
secondNumber = +prompt('Enter the second number');
valueSum = firstNumber + secondNumber;
valueSubtraction = firstNumber - secondNumber;
valueMultiplication = firstNumber * secondNumber;
valueDivision = firstNumber / secondNumber;
alert(`•  ${firstNumber} + ${secondNumber} = ${valueSum}
•  ${firstNumber} - ${secondNumber} = ${valueSubtraction}
•  ${firstNumber} * ${secondNumber} = ${valueMultiplication}
•  ${firstNumber} / ${secondNumber} = ${valueDivision}`);